#pragma once
const int GAME_LEVEL_NAME_MAX_SIZE = 64;

const int MAX_EDITOR_ACTIONS = 100000;
const int MAX_NUMBER_GAMESTATES = 1000;
const float TIME_TO_DISPLAY_LEVEL_NAME = 1.5f;

enum SCENE_TYPE
{
	ST_EDITOR,
	ST_EDIT_LEVEL,
	ST_PLAY_WORLD,
	ST_PLAY_LEVEL,
	ST_SHOW_TEXT,
	ST_MENU,
	ST_COUNT
};